// Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Job.OffchainCashoutScheduler.BitcoinApi.Models
{
    using Lykke.Job;
    using Lykke.Job.OffchainCashoutScheduler;
    using Lykke.Job.OffchainCashoutScheduler.BitcoinApi;
    using Newtonsoft.Json;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;

    public partial class CommitmentBroadcastResponse
    {
        /// <summary>
        /// Initializes a new instance of the CommitmentBroadcastResponse
        /// class.
        /// </summary>
        public CommitmentBroadcastResponse()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the CommitmentBroadcastResponse
        /// class.
        /// </summary>
        public CommitmentBroadcastResponse(IList<CommitmentBroadcastInfo> commitmentBroadcasts = default(IList<CommitmentBroadcastInfo>))
        {
            CommitmentBroadcasts = commitmentBroadcasts;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "commitmentBroadcasts")]
        public IList<CommitmentBroadcastInfo> CommitmentBroadcasts { get; set; }

    }
}
