// Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Job.OffchainCashoutScheduler.BitcoinApi.Models
{
    using Lykke.Job;
    using Lykke.Job.OffchainCashoutScheduler;
    using Lykke.Job.OffchainCashoutScheduler.BitcoinApi;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class GenerateWalletResponse
    {
        /// <summary>
        /// Initializes a new instance of the GenerateWalletResponse class.
        /// </summary>
        public GenerateWalletResponse()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the GenerateWalletResponse class.
        /// </summary>
        public GenerateWalletResponse(string address = default(string), string pubKey = default(string), string tag = default(string))
        {
            Address = address;
            PubKey = pubKey;
            Tag = tag;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "address")]
        public string Address { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "pubKey")]
        public string PubKey { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "tag")]
        public string Tag { get; set; }

    }
}
