// Code generated by Microsoft (R) AutoRest Code Generator 1.1.0.0
// Changes may cause incorrect behavior and will be lost if the code is
// regenerated.

namespace Lykke.Job.OffchainCashoutScheduler.BitcoinApi.Models
{
    using Lykke.Job;
    using Lykke.Job.OffchainCashoutScheduler;
    using Lykke.Job.OffchainCashoutScheduler.BitcoinApi;
    using Newtonsoft.Json;
    using System.Linq;

    public partial class PrivateBccTransferResponse
    {
        /// <summary>
        /// Initializes a new instance of the PrivateBccTransferResponse class.
        /// </summary>
        public PrivateBccTransferResponse()
        {
          CustomInit();
        }

        /// <summary>
        /// Initializes a new instance of the PrivateBccTransferResponse class.
        /// </summary>
        public PrivateBccTransferResponse(string transaction = default(string), string outputs = default(string))
        {
            Transaction = transaction;
            Outputs = outputs;
            CustomInit();
        }

        /// <summary>
        /// An initialization method that performs custom operations like setting defaults
        /// </summary>
        partial void CustomInit();

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "transaction")]
        public string Transaction { get; set; }

        /// <summary>
        /// </summary>
        [JsonProperty(PropertyName = "outputs")]
        public string Outputs { get; set; }

    }
}
